import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  // SkillGroupDataType,
  SkillProvider,
  SkillTree,
  SkillTreeGroup,
  SkillType,
} from "../../dist";

const treeTheme = {
  // : SkillThemeType
  borderRadius: "8px",
  nodeHoverBorder: "2px solid",
};

const gitcoinPath: SkillType[] = [
  {
    id: "gitcoin",
    title: "Get Started",
    tooltip: { content: "" },
    children: [
      {
        id: "g1",
        title: "Moonshot Collective",
        tooltip: { content: "" },
        children: [],
      },
      {
        id: "g2",
        title: "Memes, Merch and Marketing",
        tooltip: { content: "" },
        children: [],
      },
      {
        id: "g3",
        title: "Workstream X",
        tooltip: { content: "" },
        children: [
          {
            id: "g4",
            title: "squad x",
            tooltip: { content: "" },
            children: [],
          },
          {
            id: "g5",
            title: "squad y",
            tooltip: { content: "" },
            children: [],
          },
        ],
      },
      {
        id: "g6",
        title: "DAO OPS",
        tooltip: { content: "" },
        children: [],
      },
    ],
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <SkillProvider>
        <SkillTreeGroup theme={treeTheme}>
          {/* {({ skillCount }: SkillGroupDataType) => ( */}
          {() => (
            <>
              <SkillTree
                treeId="gitcoin-tree"
                title="Gitcoin"
                data={gitcoinPath}
              />
              <SkillTree
                treeId="thegraph-tree"
                title="TheGraph"
                data={gitcoinPath}
              />
              <SkillTree
                treeId="project-id"
                title="Project ID"
                data={gitcoinPath}
                description="description"
              />
            </>
          )}
        </SkillTreeGroup>
      </SkillProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
