version: '2.4'

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind redis --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - decryptnet
  api:
    image: discovery:dev
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      redis:
        condition: service_started
    ports:
      - ${API_PORT}:${API_PORT}
      # - 9229:9229  Debug port
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      API_KEY: ${API_KEY}
      AUTH_REDIS_HOST: ${AUTH_REDIS_HOST}
      AUTH_REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}
      AUTH_REDIS_PORT: ${AUTH_REDIS_PORT}
      CONFIRMATION_TOKEN_EXPIRATION: ${CONFIRMATION_TOKEN_EXPIRATION}
      IS_SECURE_COOKIE: ${IS_SECURE_COOKIE}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_SECRET: ${COOKIE_SECRET}
      REACT_APP_URL: ${REACT_APP_URL}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      CERAMIC_SEED: ${CERAMIC_SEED}
      CERAMIC_API_URL: ${CERAMIC_API_URL}
    networks:
      - decryptnet

networks:
  decryptnet:
