version: "3.7"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind redis --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - decryptnet
  api:
    image: dcompass:dev
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - postgres
      redis:
        condition: service_started
    ports:
      - ${PORT}:${PORT}
      # - 9229:9229  Debug port
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
      HOST: ${HOST}
      PORT: ${PORT}
      API_KEY: ${API_KEY}
      REACT_APP_URL: ${REACT_APP_URL}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      DID_KEY: ${DID_KEY}
      CERAMIC_API_URL: ${CERAMIC_API_URL}
    networks:
      - decryptnet

networks:
  decryptnet:
volumes:
  postgres:
    name: dcompass-db
