/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface LibBadgeInterface extends utils.Interface {
  contractName: "LibBadge";
  functions: {};

  events: {
    "ControlTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ControlTransferred"): EventFragment;
}

export type ControlTransferredEvent = TypedEvent<
  [string, string],
  { previousController: string; newController: string }
>;

export type ControlTransferredEventFilter =
  TypedEventFilter<ControlTransferredEvent>;

export interface LibBadge extends BaseContract {
  contractName: "LibBadge";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibBadgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ControlTransferred(address,address)"(
      previousController?: string | null,
      newController?: string | null
    ): ControlTransferredEventFilter;
    ControlTransferred(
      previousController?: string | null,
      newController?: string | null
    ): ControlTransferredEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
